# Generated by Django 5.1.6 on 2025-02-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='contacts',
            field=models.CharField(default='123-456-7890', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.CharField(default='Your local business', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='dislikes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='hours',
            field=models.CharField(default='9-5', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
