# Generated by Django 4.2.18 on 2025-02-23 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_app', '0002_business_contacts_business_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='city_app.video'),
        ),
    ]
